# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_senior.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_senior(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow_senior):
        MainWindow_senior.setObjectName("MainWindow_senior")
        MainWindow_senior.resize(932, 392)
        MainWindow_senior.setStyleSheet("background-color: rgb(245, 194, 17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow_senior)
        self.centralwidget.setObjectName("centralwidget")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(30, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.change_tovar = QtWidgets.QPushButton(self.centralwidget)
        self.change_tovar.setGeometry(QtCore.QRect(30, 270, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.change_tovar.setFont(font)
        self.change_tovar.setObjectName("change_tovar")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(250, 10, 671, 371))
        self.tableView.setStyleSheet("background-color: rgb(233, 241, 250);")
        self.tableView.setObjectName("tableView")
        MainWindow_senior.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_senior)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_senior)

    def retranslateUi(self, MainWindow_senior):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_senior.setWindowTitle(_translate("MainWindow_senior", "MainWindow"))
        self.add_btn.setText(_translate("MainWindow_senior", "добавить скидку"))
        self.change_tovar.setText(_translate("MainWindow_senior", "изменить цену"))
