import sys
import db
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
from PyQt5.QtSql import QSqlDatabase
class Admin_window(QMainWindow):
    def __init__(self):
        super().__init__()
        
        self.setupUi(Admin_window=self)
        self.TableView.setModel(db.get_models())
    def setupUi(self, Admin_window):
        Admin_window.setObjectName("Admin_window")
        Admin_window.resize(822, 641)
        Admin_window.setStyleSheet("background-color: rgb(245, 194, 17);")
        self.label_tov = QtWidgets.QLabel(Admin_window)
        self.label_tov.setGeometry(QtCore.QRect(300, 20, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tov.setFont(font)
        self.label_tov.setStyleSheet("")
        self.label_tov.setObjectName("label_tov")
        self.push_db = QtWidgets.QPushButton(Admin_window)
        self.push_db.setGeometry(QtCore.QRect(320, 550, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.push_db.setFont(font)
        self.push_db.setObjectName("push_db")
        self.TableView = QtWidgets.QTableView(Admin_window)
        self.TableView.setGeometry(QtCore.QRect(20, 70, 781, 281))
        self.TableView.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.TableView.setObjectName("TableView")
        self.label_3 = QtWidgets.QLabel(Admin_window)
        self.label_3.setGeometry(QtCore.QRect(30, 460, 241, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Admin_window)
        self.label.setGeometry(QtCore.QRect(40, 390, 281, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(46, 194, 126);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Admin_window)
        self.label_2.setGeometry(QtCore.QRect(30, 390, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Admin_window)
        self.lineEdit.setGeometry(QtCore.QRect(30, 420, 291, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Admin_window)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 480, 291, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(Admin_window)
        self.label_4.setGeometry(QtCore.QRect(510, 460, 241, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Admin_window)
        self.lineEdit_3.setGeometry(QtCore.QRect(510, 480, 291, 26))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Admin_window)
        self.label_5.setGeometry(QtCore.QRect(520, 390, 281, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(46, 194, 126);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Admin_window)
        self.label_6.setGeometry(QtCore.QRect(510, 390, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Admin_window)
        self.lineEdit_4.setGeometry(QtCore.QRect(510, 420, 291, 26))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(Admin_window)
        QtCore.QMetaObject.connectSlotsByName(Admin_window)

    def retranslateUi(self, Admin_window):
        _translate = QtCore.QCoreApplication.translate
        Admin_window.setWindowTitle(_translate("Admin_window", "adn"))
        self.label_tov.setText(_translate("Admin_window", "Список товаров"))
        self.push_db.setText(_translate("Admin_window", "добавить товары"))
        self.label_3.setText(_translate("Admin_window", "Товар"))
        self.label_2.setText(_translate("Admin_window", "Срок годности"))
        self.label_4.setText(_translate("Admin_window", "Изменённая цена на товар"))
        self.label_6.setText(_translate("Admin_window", "Цена на товара"))
