# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication,QMainWindow,QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_db_client(QMainWindow):
    def setupUi(self, db_client):
        db_client.setObjectName("db_client")
        db_client.resize(715, 419)
        db_client.setStyleSheet("background-color: rgb(245, 194, 17);")
        self.tableView_clin = QtWidgets.QTableView(db_client)
        self.tableView_clin.setGeometry(QtCore.QRect(0, 0, 711, 421))
        self.tableView_clin.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.tableView_clin.setObjectName("tableView_clin")

        self.retranslateUi(db_client)
        QtCore.QMetaObject.connectSlotsByName(db_client)

    def retranslateUi(self, db_client):
        _translate = QtCore.QCoreApplication.translate
        db_client.setWindowTitle(_translate("db_client", "client"))
